version: '3'
services:
  product-db:
    image: product-db
    container_name: product-db

    expose:
      - '3306'
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: ProductDb
      MYSQL_USER: AdminUser
      MYSQL_PASSWORD: AdminPassword

    volumes:
      - mysql:/var/lib/mysql

    healthcheck:
      test: "exit 0"

  product-api:
    image: product-api
    container_name: product-api

    expose:
      - '8081'
    ports:
      - "8081:8081"

    depends_on:
      product-db:
        condition: service_healthy

volumes:
  mysql: